[package]
name = "ikea-spider-experiment"
version = "0.1.0"
authors = ["Jacky Boen <jacky.boen@bartleboglehegarty.com>"]

[dependencies]
kuchiki = "*"
hyper = "*"
postgres = "*"
url = "*"
getopts = "*"
undup = "*"
